;; Generates src/regex_tables.zig, the Unicode tables of the regex
;; engine, from the JVM that runs it, so the tables are Java's
;; java.lang.Character data by construction (docs/REGEX.md §5).
;; Run from the repository root:
;;   bb test/regex/tables.clj | zig fmt --stdin > src/regex_tables.zig
;; Regenerating is a deliberate commit, never a build step.

(def max-cp 0x10FFFF)

(defn upper [c] (Character/toUpperCase (int c)))
(defn fold [c] (Character/toLowerCase (int (upper c))))

(defn runs
  "Compress the code points `cs` (ascending) with their mapped values
  `f` into [first last stride delta] runs: every code point first,
  first+stride, ... last maps to itself plus delta."
  [cs f]
  (loop [cs cs, out []]
    (if-let [[c & more] (seq cs)]
      (let [d (- (f c) c)
            nxt (first more)
            stride (if (and nxt (<= (- nxt c) 2) (= (- (f nxt) nxt) d)) (- nxt c) 1)
            [lst rest-cs] (loop [lst c, r more]
                            (let [n (first r)]
                              (if (and n (= n (+ lst stride)) (= (- (f n) n) d))
                                (recur n (rest r))
                                [lst r])))]
        (recur rest-cs (conj out [c lst stride d])))
      out)))

(defn hex [n] (if (neg? n) (str "-0x" (format "%X" (- n))) (str "0x" (format "%X" n))))

(defn emit-runs [name doc rs]
  (println (str "/// " doc))
  (println (str "pub const " name " = [_]Run{"))
  (doseq [line (partition-all 4 rs)]
    (println (str "    " (apply str (interpose " " (for [[a b s d] line] (str ".{ " (hex a) ", " (hex b) ", " s ", " d " },")))))))
  (println "};"))

(let [cps (range 0 (inc max-cp))
      up (filter #(not= (upper %) %) cps)
      fo (filter #(not= (fold %) %) cps)
      cats (loop [c 0, prev -1, out []]
             (if (> c max-cp)
               out
               (let [t (Character/getType (int c))]
                 (recur (inc c) t (if (= t prev) out (conj out [c t]))))))]
  (println "//! GENERATED by test/regex/tables.clj from java.lang.Character; do not edit.")
  (println "//!")
  (println (str "//! Java " (System/getProperty "java.version") ". The regex engine's Unicode data (docs/REGEX.md §5):"))
  (println "//! the simple case mappings `(?iu)` folds by and the general category")
  (println "//! of every code point, for `\\p{Lu}` and the like.")
  (println)
  (println "/// `.{ first, last, stride, delta }`: each code point `first`,")
  (println "/// `first + stride`, ... `last` maps to itself plus `delta`; a code")
  (println "/// point in no run maps to itself. Runs ascend and never overlap.")
  (println "pub const Run = struct { u21, u21, u2, i32 };")
  (println)
  (emit-runs "upper" "`Character.toUpperCase`." (runs up upper))
  (println)
  (emit-runs "fold" "`Character.toLowerCase(Character.toUpperCase(c))`, the key `(?iu)` compares." (runs fo fold))
  (println)
  (println "/// The general category of every code point: entry `start << 5 | category`")
  (println "/// covers `start` up to the next entry's start, the category numbered as")
  (println "/// `Character.getType` numbers it (0 `Cn`, 1 `Lu`, ... 30 `Pf`).")
  (println "pub const categories = [_]u32{")
  (doseq [line (partition-all 8 cats)]
    (println (str "    " (apply str (interpose " " (for [[c t] line] (str (hex (bit-or (bit-shift-left c 5) t)) ",")))))))
  (println "};"))
